# Special handling for transposed CSV

### Examine raw CSV content

In [1]:
with open("../bad_metadata/COACCH_MetaData_energy_demand.csv", 'r', encoding='Windows-1252') as f:
    print(f.read())

Item,Mandatory,Type,Example,
Name,X,Free entry,"Climate change impacts on energy demand by energy carrier (electricity, natural gas, and petroleum) and sector (agriculture, industry, residential, and commercial)",
Entry date,X,DDMMYYYY,,
Dataset version,,Free entry,,
Author/Contact person,X,Free entry,Shouro Dasgupta,
Short description,X,Free entry,Climate change impacts on energy demand,
Partner,X,Standardized,CMCC,
Model type/method,X,Free entry (standardized),Econometrics,
Model,,Free entry,,
Model version,,Free entry,,
Documentation,,Free entry,,
Sector,X,Standardized,Energy demand,
Keywords,X,Free entry,"climate change, energy demand, energy carrier, sectoral, socio-economic, econometrics",
SSP,X,Standardized,SSP2,
RCP,X,Standardized,"RCP2.6, RCP4.5, RCP6.0, RCP8.5",
GCM,X,Standardized,"KNMI RACMO22E, IPSL-CM5A-MR, MPI-ESM-LR, CNRM-CM5",
Variables and units,X,Free entry,Change in energy demand (%),
Time start,X,YYYY-MM-DD,2030-01-01,
Time end,X,YYYY-MM-DD,2070-01-01,
Time resolution,X,Free entry (standardized or NA),Twenty year time-period,
Spatial coverage,X,Free entry (standardized),Global,
Spatial resolution unit Europe,X,Free entry (standardized or NA),NUTS2 2013,
Spatial resolution Rest of World,,Free entry (standardized or NA),a,
Spatial projection,,Free entry (standardized),0.5°×0.5°,
Data type,X,Free entry (standardized),Table/raster/vector,
File format,X,Free entry (standardized),CSV,
Recommended citation,X,Free entry (standardized),"Schleypen, J.R., Dasgupta, S., Borsky, S., Jury, M., Š?asný, M., Bezhanishvili, L. (2019). D2.4
Impacts on Industry, Energy, Services, and Trade. Deliverable of the H2020 COACCH project.",
Other comments,,Free entry,,

### Transpose with pandas

https://stackoverflow.com/questions/39381475/can-pandas-read-a-transposed-csv

In [2]:
import pandas as pd

df = pd.read_csv("../bad_metadata/COACCH_MetaData_energy_demand.csv", skiprows=1, header=None, encoding='Windows-1252').T   # Read csv, and transpose
df.columns = df.iloc[0]                                 # Set new column names
df

,Name,Entry date,Dataset version,Author/Contact person,Short description,Partner,Model type/method,Model,Model version,Documentation,...,Time end,Time resolution,Spatial coverage,Spatial resolution unit Europe,Spatial resolution Rest of World,Spatial projection,Data type,File format,Recommended citation,Other comments
0,Name,Entry date,Dataset version,Author/Contact person,Short description,Partner,Model type/method,Model,Model version,Documentation,...,Time end,Time resolution,Spatial coverage,Spatial resolution unit Europe,Spatial resolution Rest of World,Spatial projection,Data type,File format,Recommended citation,Other comments
1,X,X,NaN,X,X,X,X,NaN,NaN,NaN,...,X,X,X,X,NaN,NaN,X,X,X,NaN
2,Free entry,DDMMYYYY,Free entry,Free entry,Free entry,Standardized,Free entry (standardized),Free entry,Free entry,Free entry,...,YYYY-MM-DD,Free entry (standardized or NA),Free entry (standardized),Free entry (standardized or NA),Free entry (standardized or NA),Free entry (standardized),Free entry (standardized),Free entry (standardized),Free entry (standardized),Free entry
3,Climate change impacts on energy demand by ene...,NaN,NaN,Shouro Dasgupta,Climate change impacts on energy demand,CMCC,Econometrics,NaN,NaN,NaN,...,2070-01-01,Twenty year time-period,Global,NUTS2 2013,a,0.5°×0.5°,Table/raster/vector,CSV,"Schleypen, J.R., Dasgupta, S., Borsky, S., Jur...",NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Drop useless rows

In [3]:
df.drop(4,inplace=True)
df.drop(2,inplace=True)
df.drop(1,inplace=True)
df.drop(0,inplace=True)
df

,Name,Entry date,Dataset version,Author/Contact person,Short description,Partner,Model type/method,Model,Model version,Documentation,...,Time end,Time resolution,Spatial coverage,Spatial resolution unit Europe,Spatial resolution Rest of World,Spatial projection,Data type,File format,Recommended citation,Other comments
3,Climate change impacts on energy demand by ene...,NaN,NaN,Shouro Dasgupta,Climate change impacts on energy demand,CMCC,Econometrics,NaN,NaN,NaN,...,2070-01-01,Twenty year time-period,Global,NUTS2 2013,a,0.5°×0.5°,Table/raster/vector,CSV,"Schleypen, J.R., Dasgupta, S., Borsky, S., Jur...",NaN

### Save cleaned up dataframe as CSV without index

In [4]:
df.to_csv("../bad_metadata/COACCH_MetaData_energy_demand_cleaned_up.csv", encoding='utf-8', index=False)

### Examine raw content of cleaned up CSV

In [6]:
with open("../bad_metadata/COACCH_MetaData_energy_demand_cleaned_up.csv", 'r', encoding='utf-8') as f:
    print(f.read())

Name,Entry date,Dataset version,Author/Contact person,Short description,Partner,Model type/method,Model,Model version,Documentation,Sector,Keywords,SSP,RCP,GCM,Variables and units,Time start,Time end,Time resolution,Spatial coverage,Spatial resolution unit Europe,Spatial resolution Rest of World,Spatial projection,Data type,File format,Recommended citation,Other comments
"Climate change impacts on energy demand by energy carrier (electricity, natural gas, and petroleum) and sector (agriculture, industry, residential, and commercial)",,,Shouro Dasgupta,Climate change impacts on energy demand,CMCC,Econometrics,,,,Energy demand,"climate change, energy demand, energy carrier, sectoral, socio-economic, econometrics",SSP2,"RCP2.6, RCP4.5, RCP6.0, RCP8.5","KNMI RACMO22E, IPSL-CM5A-MR, MPI-ESM-LR, CNRM-CM5",Change in energy demand (%),2030-01-01,2070-01-01,Twenty year time-period,Global,NUTS2 2013,a,0.5°×0.5°,Table/raster/vector,CSV,"Schleypen, J.R., Dasgupta, S., Borsky, S., Jury, M., Š?asný, M., Bezhanishvili, L. (2019). D2.4
Impacts on Industry, Energy, Services, and Trade. Deliverable of the H2020 COACCH project.",